name: Elso WorkFlow

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++ -Wall *.cpp
      - run: IFS=$'\n'; for i in 'cat input.txt'; do echo"Eredmeny: $i, \t "$i" | ./a.out ; done 