name: Elso WorkFlow

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++ -Wall *.cpp
      - run: chmod +x run_test.sh
      - run: ./run_test.sh a.out generated_output.txt
      - run: diff generated_output.txt good_output.txt