name: Elso WorkFlow

on: 
  push

jobs:
  build_AND_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
         run: g++ *.cpp -o rpg
      - name: Run test script
         run: chmod +x run_test.sh
         run: ./run_test.sh rpg generated_output.txt
      - name: Upload result file
         uses: actions/upload-artifact@v2
         with:
          name: Result
          path: generated_output.txt
      - name: Check differences
         run: diff generated_output.txt good_output.txt